# Cmake module responsible for finding glslang and shaderc_combined from the Vulkan package
# or through other means if the package cannot be found using find_package()

find_package(Vulkan COMPONENTS glslang shaderc_combined)

if(Vulkan_FOUND)
    message(STATUS "Found Vulkan package")

    if(UNIX)
        # For Linux I get errors if I link directly with the Vulkan glslang package, so 
        # I use the system glslang package instead
        find_package(glslang)

        if(glslang_FOUND)
            message(STATUS "Found glslang package")
            target_link_libraries(main PRIVATE glslang::glslang)
        else()
            find_library(glslang_lib NAMES glslang PATHS C:/Users/chapmanc7563/Desktop/Vulkan/Lib)
            if(glslang_lib)
                message(STATUS "Found glslang library at ${glslang_lib}")
                target_link_libraries(main PRIVATE ${glslang_lib})
            else()
                message(FATAL_ERROR "Could not find glslang library")
            endif()

            find_path(glslang_path NAMES glslang PATHS C:/Users/chapmanc7563/Desktop/Vulkan/Include)
            if(glslang_path)
                message(STATUS "Found glslang path at ${glslang_path}")
                target_include_directories(main PRIVATE ${glslang_path})
            else()
                message(FATAL_ERROR "Could not fine glslang path")
            endif()
        endif()

        target_link_libraries(main PRIVATE Vulkan::shaderc_combined)
    else()
        target_link_libraries(main PRIVATE Vulkan::glslang Vulkan::shaderc_combined)
    endif()
else()
    find_package(glslang)

    if(glslang_FOUND)
        message(STATUS "Found glslang package")
        target_link_libraries(main PRIVATE glslang::glslang)
    else()
        find_library(glslang_lib NAMES glslang PATHS C:/Users/chapmanc7563/Desktop/Vulkan/Lib)
        if(glslang_lib)
            message(STATUS "Found glslang library at ${glslang_lib}")
            target_link_libraries(main PRIVATE ${glslang_lib})
        else()
            message(FATAL_ERROR "Could not find glslang library")
        endif()

        find_path(glslang_path NAMES glslang PATHS C:/Users/chapmanc7563/Desktop/Vulkan/Include)
        if(glslang_path)
            message(STATUS "Found glslang path at ${glslang_path}")
            target_include_directories(main PRIVATE ${glslang_path})
        else()
            message(FATAL_ERROR "Could not fine glslang path")
        endif()
    endif()

    find_library(shaderc_lib NAMES shaderc_combined PATHS /usr/lib C:/Users/chapmanc7563/Desktop/Vulkan/Lib)
    if (shaderc_lib)
        message(STATUS "Found shaderc library at ${shaderc_lib}")
        target_link_libraries(main PRIVATE ${shaderc_lib})
    else()
        message(FATAL_ERROR "Could not find shaderc library")
    endif()

    find_path(shaderc_path NAMES shaderc PATHS /usr/include C:/Users/chapmanc7563/Desktop/Vulkan/Include)
    if(shaderc_path)
        message(STATUS "Found shaderc path at ${shaderc_path}")
        target_include_directories(main PRIVATE ${shaderc_path})
    else()
        message(FATAL_ERROR "Could not find shaderc path")
    endif()
endif()